@baseUrl = http://localhost:3000/api
# @authToken = {{authenticate.response.body.access_token}}

# @name create_user_account
POST {{baseUrl}}/users/new
Content-Type: application/json

{
    "nickname": "KaioFelipe",
    "password": "12345"
}

###