@baseUrl = http://localhost:3000/api
# @authToken = {{authenticate.response.body.access_token}}

### SESSIONS ########################
# @name login
POST {{baseUrl}}/session/login
Content-Type: application/json

{
    "nickname": "Cinthia",
    "password": "123456a"
}

###

# @name logout
POST {{baseUrl}}/session/logout

### USERS ###########################

# @name create_user_account
POST {{baseUrl}}/users/new
Content-Type: application/json

{
    "nickname": "Cinthia",
    "password": "12345"
}

###

# @name change_user_password
PUT {{baseUrl}}/users/password
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "current_password": "123456a",
    "new_password": "123456a"
}