//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "articles_tags_rel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub article_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::article::Entity",
        from = "Column::ArticleId",
        to = "super::article::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Article,
    #[sea_orm(
        belongs_to = "super::article_tag::Entity",
        from = "Column::TagId",
        to = "super::article_tag::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ArticleTag,
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Article.def()
    }
}

impl Related<super::article_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
