//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "article_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::articles_tags_rel::Entity")]
    ArticlesTagsRel,
}

impl Related<super::articles_tags_rel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticlesTagsRel.def()
    }
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        super::articles_tags_rel::Relation::Article.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::articles_tags_rel::Relation::ArticleTag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
