//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "article")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub author_id: Uuid,
    pub created_at: DateTime,
    pub cover_url: String,
    pub updated_at: Option<DateTime>,
    pub approved: bool,
    #[sea_orm(unique)]
    pub slug: String,
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub script: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cleanup_script: Option<String>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
    #[sea_orm(
        belongs_to,
        from = "author_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user: BelongsTo<super::user::Entity>,
    #[sea_orm(has_many, via = "articles_tags_rel")]
    pub article_tags: HasMany<super::article_tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
