//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "comment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub author_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_at: DateTime,
    pub is_active: bool,
    pub article_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "article_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub article: BelongsTo<Option<super::article::Entity>>,
    #[sea_orm(has_many)]
    pub comment_reports: HasMany<super::comment_report::Entity>,
    #[sea_orm(
        belongs_to,
        from = "author_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
