//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "comment_report")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub comment_id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub created_at: DateTime,
    pub solved_by: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "comment_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub comment: BelongsTo<super::comment::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User2",
        from = "solved_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user_2: BelongsTo<Option<super::user::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User1",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user_1: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
