//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "free_badge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub image: String,
    pub code: String,
    pub link: String,
    pub link_is_external: bool,
    pub created_at: DateTime,
    pub available_until: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
