//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::article::Entity as Article;
pub use super::comment::Entity as Comment;
pub use super::comment_article::Entity as CommentArticle;
pub use super::user::Entity as User;
