//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Ceo")]
    Ceo,
    #[sea_orm(string_value = "Coord")]
    Coord,
    #[sea_orm(string_value = "Editor")]
    Editor,
    #[sea_orm(string_value = "Principal")]
    Principal,
    #[sea_orm(string_value = "User")]
    User,
    #[sea_orm(string_value = "Writer")]
    Writer,
}
