//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "team_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub nickname: String,
    pub task: String,
    pub twitter: Option<String>,
    pub discord: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::team_role_team_user::Entity")]
    TeamRoleTeamUser,
}

impl Related<super::team_role_team_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamRoleTeamUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
