//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Role;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub nickname: String,
    pub password: String,
    pub created_at: DateTime,
    pub last_login: Option<DateTime>,
    pub role: Option<Role>,
    #[sea_orm(has_many)]
    pub announcements: HasMany<super::announcement::Entity>,
    #[sea_orm(has_many)]
    pub articles: HasMany<super::article::Entity>,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comment::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
