name: Deploy

on:
    workflow_call: 
      secrets:
        square_token:
          description: Authentication Token for loging in Square Cloud CLI
          required: true
        square_app_id:
          description: ID of the Square Cloud deployed application
          required: true
      inputs:
        RUST_ENV:
          default: PRODUCTION
          description: The environment which the produced code will run in
          required: true 
          type: string
        USER_INFO_API:
          description: The URL to habblive api
          required: true 
          type: string

jobs:
  deploy-to-production:
    name: Deploy
    runs-on: ubuntu-22.04
    env:
      RUST_ENV: ${{ inputs.RUST_ENV }}
      USER_INFO_API: ${{ inputs.USER_INFO_API }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build the Rust application
        run: cargo build --release

      - name: Build the front-end
        run: |
          npm install
          npm run build

      - name: Make __package directory
        run: mkdir -p __package/www

      - name: Copy most important files to the __package directory
        run: |
          cp ./target/release/samambaia __package
          cp ./start.sh __package

          if [ -d "public" ]; then
            mv public _public
            cp -a _public __package
          fi

          if [ -d "dist" ]; then
            cp -a dist __package
          fi
          
          cp package-lock.json __package
          cp package.json __package
          cp Cargo.toml __package
          cp Cargo.lock __package
          cp www/root.html __package/www

      - name: Setup Square Cloud
        uses: squarecloudofc/github-action@v2
        with:
          token: ${{ secrets.square_token }}
          install-only: true

      - name: Commit the application to the host
        run: |
          cd __package
          squarecloud login --token=${{ secrets.square_token }}
          squarecloud commit ${{ secrets.square_app_id }}
          squarecloud app restart ${{ secrets.square_app_id }}