name: Cargo Clippy & Cargo Format

on:
  workflow_call: 

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: warn

jobs:
  check_linting:
    name: "assert rust-clippy patterns are followed"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - name: Cache Linting Artifacts
        uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings

  check_code_fmt:
    name: "check code format and linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly
      - run: rustup default nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt --all -- --check