name: CI/CD Pipeline

on:
  pull_request: 
  push: 

jobs:
  linting:
    uses: ./.github/workflows/linting.yaml

  tests:
    uses: ./.github/workflows/tests.yaml

  deploy:
    needs: [linting, tests]
    if: github.ref_name == 'main' && github.ref_type == 'branch' &&  github.event_name == 'push'
    secrets:
      square_token: ${{ secrets.SQUARE_TOKEN }}
      square_app_id: ${{ secrets.MAIN_SQUARE_APPLICATION_ID }}
    uses: ./.github/workflows/deploy.yaml

  deploy_staging:
    needs: [linting, tests]
    if: github.ref_name == 'staging' && github.ref_type == 'branch' &&  github.event_name == 'push'
    secrets:
      square_token: ${{ secrets.SQUARE_TOKEN }}
      square_app_id: ${{ secrets.STAGING_SQUARE_APPLICATION_ID }}
    uses: ./.github/workflows/deploy.yaml
