name: Cargo Test

on:
  workflow_call: 

env: 
  CARGO_TERM_COLOR: always
  RUST_LOG: warn

jobs:
  build_and_test:
    name: "run crate tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - run: cp .env.test .env
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - name: Cache Test Build Artifacts
        uses: Swatinem/rust-cache@v2
      - run: cargo test --verbose --all-features